apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "@daily"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: garbage-collection
            image: analytics-kubelet-055005d.private-us-east-1.github.net:30550/argo-ml:latest
            args:
            - python
            - gc_cleanup.py --max_age_hrs 168 --adhoc
          restartPolicy: OnFailure
