apiVersion: v1
kind: Service
metadata:
  name: argo-validation-controller
  namespace: argo
spec:
  ports:
  - name: webhook
    port: 8443
    targetPort: 8443
  selector:
    name: argo-validation-controller
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: argo-validation-controller
  namespace: argo
  labels:
    name: argo-validation-controller
spec:
  replicas: 3
  template:
    metadata:
      name: argo-validation-controller
      labels:
        name: argo-validation-controller
    spec:
      containers:
        - name: webhook
          image: analytics-kubelet-055005d.private-us-east-1.github.net:30550/argo-validation:latest
          imagePullPolicy: Never
          volumeMounts:
            - name: webhook-certs
              mountPath: /certificates/
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
          ports:
          - name: http
            containerPort: 8443
            protocol: TCP
      volumes:
        - name: webhook-certs
          secret:
            secretName: argo-validation-certs
---
kind: ValidatingWebhookConfiguration
metadata:
  name: scheduling-admission
webhooks:
  - name: argo-validation-controller.argo
    rules:
      - apiGroups:
          - "argoproj.io"
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
        resources:
          - hyperparamworkflows
    failurePolicy: Ignore
    clientConfig:
      service:
        name: argo-validation-controller
        namespace: argo
        path: "/"
      caBundle: ${CA_BUNDLE}